### ISSUE TITLE
Update new footer center panel alignment and spacing

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/lux-design-system#308] opened 2024-08-05 13:25 UTC
### Current display
![Screenshot 2024-08-05 at 9 18 05 AM](https://github.com/user-attachments/assets/143462af-7376-4af7-b262-e26ecebdeb70)

### Desired display

![Screenshot 2024-08-05 at 9 17 56 AM](https://github.com/user-attachments/assets/707f0f23-4abc-408e-be0c-4cfd70e31a4d)

### Acceptance criteria

- [ ] search box is wider, and center-aligned
- [ ] search box has a black background
- [ ] logos below search box have more spacing between them and consistent vertical alignment
- [ ] font for text above search box is less heavy, "Newsletter" is lowercased.
- [ ] I can successfully use this feature with Voice Over in Safari.
- [ ] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave
- [ ] ...

**Comment by christinach** [comment] 2024-08-05 13:40
duplicate of #305

**Closed by christinach** 2024-08-05 13:40 UTC

**Comment by hackartisan** [comment] 2024-08-05 13:42
@christinach #305 only talks about the social buttons. Do you want to update it to include the search box color / size / alignment and adjustments to the newsletter subscription text?
